name: Go
on:
  pull_request:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.19.3
      uses: actions/setup-go@v1
      with:
        go-version: 1.19.3
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Run go mod download
      run: go mod download
    - name: Install golangci-lint
      run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s v1.23.6
    - name: Run golangci-lint
      run: >
        ./bin/golangci-lint run
        --tests
        #  --enable-all
        #  --disable gochecknoglobals
        #  --disable gochecknoinits
    # - name: Run tests
    #   run: go test -race -v ./...
